nme: Crone jobs
 
on:
  schedule:
    - cron: "0 0  * * * " 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "hello from github action"
      - name: Print the current data and time 
        run: date     