name: Cron

on:
  push:
    branches: [main]
  schedule:
    - cron: "* 19 * * *"
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "hello from github action"

      - name: Print current date and time
        run: date